export const ActivityFormProps = [
  {
    nature: "full",
    type: "text",
    label: "subject",
    Title: "Subject",
    placeholder: "Enter activity subject",
    required: true,
  },
  {
    nature: "half",
    type: "dropdown",
    label: "activity_type",
    Title: "Activity Type",
    placeholder: "Select type",
    required: true,
    option: ["Call", "Meeting", "Task", "Email", "Note"],
  },
  {
    nature: "half",
    type: "stage-dropdown",
    label: "priority",
    Title: "Priority",
    placeholder: "Medium",
    option: ["Low", "Medium", "High", "Urgent"],
  },
  {
    nature: "half",
    type: "dropdown",
    label: "related_to",
    Title: "Related To",
    placeholder: "Select type",
    required: true,
    option: ["Deal", "Service Site", "Parent Company"],
  },
  {
    nature: "half",
    type: "search-dropdown",
    label: "related_to_id",
    Title: "Related Item",
    placeholder: "Select item",
    required: true,
    linkTable: "contacts",
    linkTableValue: ["first_name", "last_name"],
  },
  {
    nature: "half",
    type: "date",
    label: "due_date",
    Title: "Due Date",
    placeholder: "Pick a date",
  },
  {
    nature: "half",
    type: "time",
    label: "due_time",
    Title: "Due Time",
    placeholder: "09:00 AM",
  },
  {
    nature: "half",
    type: "dropdown",
    label: "contact_id",
    Title: "Contact",
    placeholder: "Select Related Item first",
    linkTable: "contacts",
    linkTableValue: ["first_name", "last_name"],
  },
  {
    nature: "half",
    type: "dropdown",
    label: "assigned_to",
    Title: "Assign To",
    placeholder: "Select user (leave empty for self)",
    linkTable: "users",
    linkTableValue: "full_name",
  },
  {
    nature: "full",
    type: "textarea",
    label: "description",
    Title: "Description",
    placeholder: "Enter activity description, notes, or instructions...",
    rows: 4,
  },
  {
    sectionName: "button",
    button: ["Cancel", "Create Activity"],
  },
];
export const activityLinkTable = [
  'contacts', 'users', 'activities', 'activity_types', 'activity_priorities', 'activity_related_to', 'activity_related_to_id'
];
