export const ActivityFormProps = [
  {
    nature: "full",
    type: "text",
    label: "Subject",
    placeholder: "Enter activity subject",
    required: true,
  },
  {
    nature: "half",
    type: "dropdown",
    label: "Activity Type",
    placeholder: "Select type",
    required: true,
    option: ["Call", "Meeting", "Task", "Email", "Note"],
  },
  {
    nature: "half",
    type: "stage-dropdown",
    label: "Priority",
    placeholder: "Medium",
    option: ["Low", "Medium", "High", "Urgent"],
  },
  {
    nature: "half",
    type: "dropdown",
    label: "Related To",
    placeholder: "Select type",
    required: true,
    option: ["Deal", "Service Site", "Parent Company"],
  },
  {
    nature: "half",
    type: "search-dropdown",
    label: "Related Item",
    placeholder: "Select item",
    required: true,
    option: [
      "Enterprise Software License Renewal",
      "Cloud Migration & Infrastructure Upgrade",
      "Custom CRM Integration",
      "Patient Portal Modernization",
      "POS System Rollout (Phase 2)",
    ],
  },
  {
    nature: "half",
    type: "date",
    label: "Due Date",
    placeholder: "Pick a date",
  },
  {
    nature: "half",
    type: "time",
    label: "Due Time",
    placeholder: "09:00 AM",
  },
  {
    nature: "half",
    type: "dropdown",
    label: "Contact",
    placeholder: "Select Related Item first",
    option: [
      "John Smith",
      "Sarah Johnson",
      "Michael Brown",
      "Emily Davis",
      "David Wilson",
    ],
  },
  {
    nature: "half",
    type: "dropdown",
    label: "Assign To",
    placeholder: "Select user (leave empty for self)",
    option: [
      "Assign to me",
      "Dead",
      "Michael Torres",
      "Emma Rodriguez",
      "David Anderson",
    ],
  },
  {
    nature: "full",
    type: "textarea",
    label: "Description",
    placeholder: "Enter activity description, notes, or instructions...",
    rows: 4,
  },
  {
    sectionName: "button",
    button: ["Cancel", "Create Activity"],
  },
];
